version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: "no"
    ports:
      - "${PGPORT}:5432"
    volumes:
      - longformdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_DB: "${PGDATABASE}"
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  longformdata:
   driver: local